<?php

namespace Kod\Bundle\CaixaBundle\Repository;

/**
 * LancamentoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LancamentoTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
