<?php

namespace Kod\Bundle\CaixaBundle\Repository;

/**
 * ProfissionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfissionalRepository extends \Doctrine\ORM\EntityRepository
{
}
