<?php

namespace Kod\Bundle\CaixaBundle\Repository;

/**
 * ServicosTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicosTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
