<?php

namespace Kod\Bundle\FinanceiroBundle\Repository;

/**
 * ContaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContaRepository extends \Doctrine\ORM\EntityRepository
{
}
