<?php

namespace Kod\Bundle\FinanceiroBundle\Repository;

/**
 * FormaPagamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormaPagamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
