<?php

namespace Kod\Bundle\EstoqueBundle\Repository;

/**
 * ProdutosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdutosRepository extends \Doctrine\ORM\EntityRepository
{
}
